### ISSUE TITLE
there is no self.cost_matrix in the Tracker Class

### ISSUE THREAD

**Issue by matthew9655** [kelvin95/csc490-projects#2]
the todo tells us to use self.cost_matrix but there is no initialization of self.cost_matrix in the Tracker class. I tried calling the cost_matrix function in associate_greedy and associate_hungarian but i get `NameError: name 'cost_matrix' is not defined`. Please advice.

**Comment by matthew9655** [comment]
@kelvin95 @ajyang99

**Comment by ajyang99** [comment]
`cost_matrix` is a member function of the `Tracker` class that you are supposed to implement, it's a function call (i.e., it should be invoked with`self.cost_matrix(bboxes1, bboxes2)`), does that make sense to you?

**Comment by matthew9655** [comment]
I see. I misunderstood. Thank you @ajyang99!

**Comment by ajyang99** [comment]
No problem, let us know here or on quercus if you have other questions as well!
